[package]
name = "buf-ref-reader"
version = "0.1.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]
edition = "2018"

[dependencies]
# TODO configurable?
memchr = { version = "2", default-features = false, features = ["libc"]}

[dev-dependencies]
fnv = "1"
